
import { StyleSheet } from "react-native";
const OpenEnquiryStyles = StyleSheet.create({
  background: {
    flex: 1,
    width: "100%",
    height: "100%",
    justifyContent: "center",
  },
  container: {
    flex: 1,
    padding: 10,
    backgroundColor: "transparent",
    marginTop:5
  },
  tabsContainer: {
    flexDirection: "row",
    marginBottom: 10,
  },
  tab: {
    flex: 1,
    paddingVertical: 8,
    backgroundColor: "#D9D9D9",
    marginHorizontal: 2,
    borderRadius: 5,
    marginTop: 30,
  },
  activeTab: {
    backgroundColor: "transparent",
  },
  tabText: {
    textAlign: "center",
    fontWeight: "bold",
    color: "#250588",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
  },
  activeTabText: {
    color: "#D9D9D9",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
    marginTop: 20,
    justifyContent: "space-between",
  },
  searchInput: {
    flex: 1,
    backgroundColor: "#D9D9D9",
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 50,
    fontSize: 14,
  },
  plusButton: {
    backgroundColor: "#6072C7",
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 10,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    width: "70%",
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  cardText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#6072C7',
    textAlign: 'center',
  },
  closeButton: {
    backgroundColor: "#6072C7",
    padding: 10,
    borderRadius: 8,
    width: '40%',
    marginTop: 10,
    alignItems: "center",
  },
  card: {
    backgroundColor: "#6072C7",
    marginBottom: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
  },
  modalcard: {
    marginBottom: 10,
    height: 50,
    shadowColor: "#000",
    borderWidth: 1,
    borderColor: "#6072C7",
    justifyContent: "center",
    alignItems: "center",
    width: "60%",
  },
  totalCountTextlabel: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#f0f0f0ff",
    marginBottom: 5,
    marginLeft: 5,
  },
  totalCountTextValue: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#ebebebff",
    marginLeft: 5,
  },
  headerText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 15,
    marginTop: 5,
    marginHorizontal: 5,
  },
  miniCard: {
    backgroundColor: "#e8e7e7ff",
    borderRadius: 5,
    padding: 5,
  },
  title: {
    fontSize: 13,
    fontWeight: "bold",
    marginBottom: 8,
    color: "#250588",
  },
  label: {
    fontWeight: "bold",
    color: "#878585ff",
    fontSize: 10,
  },
  value: {
    fontWeight: "bold",
    color: "#250588",
    fontSize: 12,
    textAlign: "center",
  },
    invoicevalue: {
    fontWeight: "bold",
    color: "#250588",
    fontSize: 12,
    textAlign: "center",
  },
  loader: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loaderText: {
    marginTop: 10,
    fontSize: 16,
    color: "#250588",
  },
  center: {
    justifyContent: "center",
    alignItems: "center",
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 5,
    alignItems: "center",
  },
  belowrow: {
    flexDirection: "row",
    marginBottom: 5,
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: "#acaaaaff",
  },
infoRow: {
  flexDirection: "row",
  justifyContent: "space-between",
  alignItems: "center",
  marginVertical: 6,
  flexWrap: "wrap", 
},
  infoItem: {
    flex: 1,
    alignItems: "center",
  },
  extraContainer: {
    padding: 5,
    marginTop: 5,
    borderRadius: 5,
  },
  extraRowBelow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 5,
    marginBottom: 5,
  },
  extraItem: {
    flex: 1,
    alignItems: "center",
  },
    extraItem1: {
    flex: 1,
    alignItems: "flex-start",
    marginLeft:"9%"
  },
  extraLabel: {
    fontSize: 10,
    color: "#E5E4E4",
    fontWeight: "bold",
  },
  extraValue: {
    fontSize: 12,
    color: "#FFFFFF",
    fontWeight: "bold",
    textAlign: "center",
  },
  summaryCard: {
    backgroundColor: "transparent",
    borderRadius: 1,
    padding: 15,
    marginTop: 15,
    marginBottom: 15,
    shadowColor: "#ffffffff",
    shadowOpacity: 8,
    shadowOffset: { width: 10, height: 10 },
    shadowRadius: 8,
    elevation: 2,
  },
  summaryHeader: { flexDirection: "row", alignItems: "center", marginBottom: 15 },
  summaryHeaderText: { fontSize: 14, fontWeight: "600", color: "#24bc99"},
  viewproduct: { fontSize: 12, fontWeight: "600", color: "#250588",textDecorationLine:"underline"},
 productName: {
  flex: 1, 
  fontSize: 13,
  fontWeight: "500",
  color: "#ffffff",
  fontFamily: 'Inter-Bold',
  marginLeft: 10,
  marginRight: 8,
  flexShrink: 1, 
  flexWrap: "wrap",
},

productvalue: {
  fontWeight: "bold",
  color: "#eeeeeeff",
  fontSize: 12,
  textAlign: "right",
  minWidth: 40, 
},
  OutstangingLabel: {
    fontSize: 13,
    fontWeight: "bold",
    color: "#989898ff",
    marginLeft: 4,
  },
  OutstangingValue: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#fff",
    marginLeft: 4,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  summaryItem: {
    flex: 1,
    alignItems: "center",
  },
  summaryLabel: {
    fontSize: 12,
    color: "#bbb",
    marginBottom: 4,
  },
  summaryValue: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#fff",
  },
horizontalButtonContainer: {
  marginBottom: 20,
},
horizontalButton: {
  backgroundColor: "#6072C7",
  paddingVertical: 10,
  paddingHorizontal: 30,
  borderRadius: 25,
  marginRight: 10,
  alignItems: "center",
  justifyContent: "center",
},
horizontalButtonText: {
  color: "#fff",
  fontWeight: "bold",
  fontSize: 12,
},
}); 
export default OpenEnquiryStyles;