export default {

  POST_POSTAUTHENDICATION_REQUEST: 'POST_POSTAUTHENDICATION_REQUEST',
  POST_POSTAUTHENDICATION_SUCCESS: 'POST_POSTAUTHENDICATION_SUCCESS',
  POST_POSTAUTHENDICATION_FAILURE: 'POST_POSTAUTHENDICATION_FAILURE',
  POST_POSTAUTHENDICATION_FAILURE_INVALID: 'POST_POSTAUTHENDICATION_FAILURE_INVALID',

  POST_CREATEVISIT_REQUEST: "POST_CREATEVISIT_REQUEST",
  POST_CREATEVISIT_SUCCESS: "POST_CREATEVISIT_SUCCESS",
  POST_CREATEVISIT_FAILURE: "POST_CREATEVISIT_FAILURE",
  POST_CREATEVISIT_FAILURE_INVALID: "POST_CREATEVISIT_FAILURE_INVALID",

  POST_CUSTOMERLIST_REQUEST: "POST_CUSTOMERLIST_REQUEST",
  POST_CUSTOMERLIST_SUCCESS: "POST_CUSTOMERLIST_SUCCESS",
  POST_CUSTOMERLIST_FAILURE: "POST_CUSTOMERLIST_FAILURE",
  POST_CUSTOMERLIST_FAILURE_INVALID: "POST_CUSTOMERLIST_FAILURE_INVALID",

  POST_OUTSTANDING_REQUEST: "POST_OUTSTANDING_REQUEST",
  POST_OUTSTANDING_SUCCESS: "POST_OUTSTANDING_SUCCESS",
  POST_OUTSTANDING_FAILURE: "POST_OUTSTANDING_FAILURE",
  POST_OUTSTANDING_FAILURE_INVALID: "POST_OUTSTANDING_FAILURE_INVALID",

  POST_NEWVISIT_REQUEST: "POST_NEWVISIT_REQUEST",
  POST_NEWVISIT_SUCCESS: "POST_NEWVISIT_SUCCESS",
  POST_NEWVISIT_FAILURE: "POST_NEWVISIT_FAILURE",
  POST_NEWVISIT_FAILURE_INVALID: "POST_NEWVISIT_FAILURE_INVALID",

  ODOO_CALL_REQUEST: 'ODOO_CALL_REQUEST',
  ODOO_CALL_SUCCESS: 'ODOO_CALL_SUCCESS',
  ODOO_CALL_FAILURE: 'ODOO_CALL_FAILURE',

  POST_ACCESSREAD_REQUEST: "POST_ACCESSREAD_REQUEST",
  POST_ACCESSREAD_SUCCESS: "POST_ACCESSREAD_SUCCESS",
  POST_ACCESSREAD_FAILURE: "POST_ACCESSREAD_FAILURE",
  POST_ACCESSREAD_FAILURE_INVALID: "POST_ACCESSREAD_FAILURE_INVALID",

  POST_CONVERT_REQUEST: "POST_CONVERT_REQUEST",
  POST_CONVERT_SUCCESS: "POST_CONVERT_SUCCESS",
  POST_CONVERT_FAILURE: "POST_CONVERT_FAILURE",
  POST_CONVERT_FAILURE_INVALID: "POST_CONVERT_FAILURE_INVALID",

  CLEAR_SOPRODUCTS: "CLEAR_SOPRODUCTS",
  CLEAR_SONUMBERDETAIL: "CLEAR_SONUMBERDETAIL",

  CLEAR_LOGIN_FIELDS: 'CLEAR_LOGIN_FIELDS',
}